In [2]:
import pandas
import numpy

In [5]:
paal_df = pandas.read_csv('./data/PAAL_ORDER_HISTORY.csv')
paal_df

,Time,Type,Pair,Side,Price,Amount,Executed,Average Price,Status
2024-06-04 20:08:02,Exchange,PAAL/USDT,Buy,Market Price,10.7723,31.187920,0.3454,Executed,NaN
2024-06-03 01:26:22,Exchange,PAAL/USDT,Buy,Market Price,10.0000,28.081999,0.3560,Executed,NaN
2024-05-31 23:48:01,Exchange,PAAL/USDT,Buy,0.3505,71.3266,71.326600,0.3505,Executed,NaN
2024-05-30 23:54:03,Exchange,PAAL/USDT,Buy,Market Price,10.0000,26.925148,0.3713,Executed,NaN
2024-05-30 12:32:22,Exchange,PAAL/USDT,Buy,0.3600,27.8055,27.805500,0.3600,Executed,NaN
2024-05-29 15:23:56,Exchange,PAAL/USDT,Buy,0.3650,27.4246,27.424600,0.3650,Executed,NaN
2024-05-29 00:53:00,Exchange,PAAL/USDT,Buy,0.3800,34.2104,34.210400,0.3800,Executed,NaN
2024-05-28 19:29:55,Exchange,PAAL/USDT,Buy,Market Price,15.0000,37.660055,0.3982,Executed,NaN
2024-05-27 22:26:36,Exchange,PAAL/USDT,Buy,Market Price,10.0000,23.854962,0.4191,Executed,NaN
2024-05-26 14:22:45,Exchange,PAAL/USDT,Buy,Market Price,10.9872,26.341960,0.4170,Executed,NaN
2024-05-26 09:22:04,Exchange,PAAL/USDT,Buy,0.4150,24.0987,24.098700,0.4150,Executed,NaN
2024-05-25 20:08:46,Exchange,PAAL/USDT,Buy,Market Price,10.0000,23.277467,0.4295,Executed,NaN
2024-05-25 13:16:32,Exchange,PAAL/USDT,Buy,0.4300,23.2581,23.258100,0.4300,Executed,NaN
2024-05-24 15:50:05,Exchange,PAAL/USDT,Buy,0.4505,22.1997,22.199700,0.4505,Executed,NaN
2024-05-24 11:31:24,Exchange,PAAL/USDT,Buy,Market Price,10.0000,21.372088,0.4678,Executed,NaN
2024-05-18 15:08:49,Exchange,PAAL/USDT,Buy,0.4500,22.2444,22.244400,0.4500,Executed,NaN
2024-05-14 20:50:53,Exchange,PAAL/USDT,Buy,Market Price,10.0000,27.203482,0.3675,Executed,NaN
2024-05-13 10:10:08,Exchange,PAAL/USDT,Buy,0.3800,39.4736,39.473600,0.3800,Executed,NaN
2024-05-11 11:35:50,Exchange,PAAL/USDT,Buy,0.4000,40.0000,40.000000,0.4000,Executed,NaN
2024-05-07 01:07:39,Exchange,PAAL/USDT,Buy,0.4100,59.4416,59.441600,0.4100,Executed,NaN
2024-05-07 01:07:27,Exchange,PAAL/USDT,Buy,0.4250,47.0588,47.058800,0.4250,Executed,NaN
2024-05-06 23:42:29,Exchange,PAAL/USDT,Buy,0.4500,22.2444,22.244400,0.4500,Executed,NaN
2024-05-06 23:42:06,Exchange,PAAL/USDT,Buy,0.4800,20.8541,20.854100,0.4800,Executed,NaN
2024-05-06 19:43:19,Exchange,PAAL/USDT,Buy,0.5000,20.0000,20.000000,0.5000,Executed,NaN

In [37]:
amount_buy = [10, 10, 10, 20, 24, 16, 15, 10, 10, 10, 10, 10, 10, 10, 11, 10, 15, 13, 10, 10, 10, 25, 10, 11]
column_name = ["Buy ($)"]

paal_df = pandas.DataFrame(amount_buy, columns=column_name)
print(f"${paal_df.sum()[0]}")
paal_df

$300

C:\Users\User\AppData\Local\Temp\ipykernel_8348\4267503163.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"${paal_df.sum()[0]}")

    Buy ($)
0        10
1        10
2        10
3        20
4        24
5        16
6        15
7        10
8        10
9        10
10       10
11       10
12       10
13       10
14       11
15       10
16       15
17       13
18       10
19       10
20       10
21       25
22       10
23       11